fix "error executing lua callback ... attempt to concatenate local 'method' (a table value)"
nvimtools/none-ls.nvim pull request #211
Opened 2024-11-30 16:47 UTC by bartman

After updating my plugins I his this error, while editing a shell script.  Other LSPs seem to work fine.

```
Error detected while processing InsertLeave Autocommands for "*":
Error executing lua callback: .../.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/rpc.lua:131: attempt to concatenate local 'method' (a table value)
stack traceback:
        .../.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/rpc.lua:131: in function 'notify'
        ...art/usr/neovim/share/nvim/runtime/lua/vim/lsp/client.lua:784: in function 'notify'
        ...ocal/share/nvim/lazy/none-ls.nvim/lua/null-ls/client.lua:205: in function 'notify_client'
        .../.local/share/nvim/lazy/none-ls.nvim/lua/null-ls/rpc.lua:149: in function 'flush'
        ....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/init.lua:49: in function <....local/share/nvim/lazy/none-ls.nvim/lua/null-ls/init.lua:48>
```

It would seem that the `method` passed to `dispatchers.notify()` method is a table, not a string.

I have used `vim.inspect(method)` to convert that `method` table to a string before concatenation.

Problem went away, LSP working fine in bash.

2024-11-30 23:17 UTC, mochaaP commented
I believe this is likely the same issue with #209.

Are you using nightly?

2024-11-30 23:54 UTC, mochaaP commented
I could not reproduce this. Can you attach an example of the table in question?

2024-11-30 23:57 UTC, mochaaP requested changes
`method` MUST be a string. see `:h vim.lsp.rpc.start()`.

2024-12-01 05:55 UTC, jiangyinzuo commented
https://github.com/nvimtools/none-ls.nvim/blob/8fd7b29648a48502f1aa72ffe0c19e56069258c6/lua/null-ls/client.lua#L204-L209

I met the same problem. I changed the line 205 `client:notify(method, params)` to `client.notify(method, params)`, then it works.

2024-12-01 08:34 UTC, mochaaP commented
hi @jiangyinzuo, what neovim commit are you on?

2024-12-01 09:13 UTC, jiangyinzuo commented
> hi @jiangyinzuo, what neovim commit are you on?

Oh, I updated to the latest commit and then no error occurred. Thanks.

2024-12-01 10:29 UTC, mochaaP commented
tldr: update to latest nightly.

2024-12-01 10:29 UTC, closed without merging

2024-12-30 21:12 UTC, bartman commented
I updated nvim and none-ls.nvim to latest commits, and problem went away.

thank you.