Validate Formatter Exit Codes
nvimtools/none-ls.nvim pull request #221
Opened 2024-12-19 21:08 UTC by barrett-ruth

- **feat(formatting): validate format exit codes**
- **fix(helper): default valid format codes to 0**

2024-12-19 21:14 UTC, barrett-ruth commented
@mochaaP I can't assign reviewers so please take a look. I know I need to squash commits and a bunch of other stuff but I just wanted to draft the initial API. Let me know everything that can be improved.

2024-12-22 18:59 UTC, barrett-ruth commented
@mochaaP I'm going to start going through the formatters one-by-one (pain) to ensure I'm passing the right exit code. 

1. Is there a better way to do this?
2. I currently make it optional (and default to exit code 0) to indicate formatter success in `check_exit_code`. Is this fine?

2024-12-22 19:04 UTC, mochaaP commented
I think (2) is fine.

For (1), we could land the changes first and wait for feedback from ones who actually use them if any problem arises.

2024-12-22 19:36 UTC, barrett-ruth commented
Ready for review.

2024-12-25 04:29 UTC, mochaaP requested changes

2024-12-25 04:29 UTC, mochaaP commented on lua/null-ls/helpers/formatter_factory.lua
> +        vim.print(opts)
Forgot to clean up a debug print?

2024-12-25 04:29 UTC, mochaaP commented on lua/null-ls/helpers/check_exit_code.lua
> +end
duplicated here:

https://github.com/nvimtools/none-ls.nvim/blob/main/lua%2Fnull-ls%2Fhelpers%2Fgenerator_factory.lua#L135-L140

2024-12-25 04:29 UTC, mochaaP commented on lua/null-ls/helpers/formatter_factory.lua
> +    if opts.check_exit_code == nil then
Set `check_exit_code` in the generator factory instead of here.

2024-12-28 13:56 UTC, barrett-ruth commented
@mochaaP addressing comments above but this is a longer response:

The problem I have with moving the code to the generic factory (and this includes the code duplication comment above) is that I thought this feature only makes sense for formatters.

If we added this to generator factory, wouldn't we also be checking linting exit codes as well?

2025-01-04 18:46 UTC, barrett-ruth commented
@mochaaP this is ready for review, see above comments

2025-01-04 23:36 UTC, barrett-ruth commented
What does the eyes emoji mean :sob: I've already addressed the comments I thought... what do you think? (lol)

2025-01-05 00:32 UTC, mochaaP commented
“I will take a look at it” 😂 This needs some slight changes, I will take care of it.

2025-01-05 10:57 UTC, mochaaP commented
Do you think this implementation is okay?

2025-01-05 19:29 UTC, barrett-ruth commented
I see. You just set the exit code to `0` in the code and then that's picked up later in the parsing.

Much cleaner implementation, LGTM.

2025-01-05 19:32 UTC, barrett-ruth commented
@mochaaP you updated the logging message to use `logger:add_entry`.

Then you deleted the file containing that change (`check_exit_code`) - lol! I'm wondering if this was intentional? I thought we wanted this informative message to the end user?

If this is the case, I thought we had to separate the logic out in another file to do that log... because *only* in the formatters does the notion of validating the exit code make sense.

Sorry this is taking so long, LMK if you know what I'm saying.

2025-01-05 23:08 UTC, mochaaP commented
ack, will check tonight.

2025-01-07 06:46 UTC, barrett-ruth commented
LGTM!

2025-01-07 09:45 UTC, merged

2025-01-09 09:24 UTC, geril2207 commented
@mochaaP @barrett-ruth 
prettierd nvim(nightly but idk if it changes anything):

https://github.com/user-attachments/assets/32938e71-b5d5-430f-ba95-b89c35eaacea

before:

https://github.com/user-attachments/assets/ccdb13ba-d102-472c-a25f-19be9b010b9e

2025-01-09 09:29 UTC, mochaaP commented
cc @barrett-ruth is prettierd outputting to stdout? we might need to ignore that

2025-01-10 19:37 UTC, daephx commented
Found myself here because I updated none-ls and keep getting the error `nvim_echo must not be called in a lua loop callback` when the buffer has invalid syntax. I've only tested with `stylua`, and haven't checked other formatters.

The error output itself is rather annoying, so for now my solution is to pin none-ls to commit 83c7c00.

2025-01-11 01:19 UTC, mochaaP commented
I've partially reverted this until I figure out a better way to present the error message.